<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Version>1.1.0.0</Version>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <FileVersion>1.1.0.0</FileVersion>
    <InformationalVersion>1.1.0.0</InformationalVersion>
    <OutputPath>$(MSBuildThisFileDirectory)$(Configuration)\bin\$(MSBuildProjectName)\</OutputPath>
    <IntermediateOutputPath>$(MSBuildThisFileDirectory)$(Configuration)\obj\$(MSBuildProjectName)\</IntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(MSBuildThisFileDirectory)$(Configuration)\obj\$(MSBuildProjectName)\</MSBuildProjectExtensionsPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildThisFileDirectory)Debug\**;$(MSBuildThisFileDirectory)Release\**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
